version: '3'
services:

  zookeeper:
    container_name: cluster_zookeeper
    image: wurstmeister/zookeeper:3.4.6
    networks:
      - kafkanetwork
    restart: unless-stopped
    ports:
      - "2181:2181"

  kafka:
    container_name: cluster_kafka
    image: wurstmeister/kafka:1.0.0
    ports:
      - "9092:9092"
    networks:
      - kafkanetwork
    environment:
      KAFKA_CREATE_TOPICS: "add-topic:1:1,sub-topic:1:1,mul-topic:1:1,div-topic:1:1,results-topic:1:1,final-topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: cluster_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
    links:
      - "zookeeper:cluster_zookeeper"
    restart: unless-stopped
    depends_on:
      - zookeeper

  discovery:
    build: ./discovery-service
    container_name: ds
    ports:
      - "8761:8761"
    networks:
      - kafkanetwork
    environment:
      - HOSTNAME=discovery-service
      - PORT=8761
    restart: unless-stopped

  operation-generator-1:
    build: ./operation-generator
    ports:
      - "8081:8081"
    networks:
      - kafkanetwork
    environment:
      - EUREKA_URI=http://ds:8761/eureka
      - KAFKA_ADDRESS=cluster_kafka:9092
      - PROFILE=add
    depends_on:
      - discovery
      - kafka
    links:
      - "discovery:ds"
      - "kafka:cluster_kafka"
    restart: unless-stopped

  operation-generator-2:
    build: ./operation-generator
    ports:
      - "8082:8081"
    networks:
      - kafkanetwork
    environment:
      - EUREKA_URI=http://ds:8761/eureka
      - KAFKA_ADDRESS=cluster_kafka:9092
      - PROFILE=sub
    depends_on:
      - discovery
      - kafka
    links:
      - "discovery:ds"
      - "kafka:cluster_kafka"
    restart: unless-stopped

  operation-generator-3:
    build: ./operation-generator
    ports:
      - "8083:8081"
    networks:
      - kafkanetwork
    environment:
      - EUREKA_URI=http://ds:8761/eureka
      - KAFKA_ADDRESS=cluster_kafka:9092
      - PROFILE=mul
    depends_on:
      - discovery
      - kafka
    links:
      - "discovery:ds"
      - "kafka:cluster_kafka"
    restart: unless-stopped

  operation-generator-4:
    build: ./operation-generator
    ports:
      - "8084:8081"
    networks:
      - kafkanetwork
    environment:
      - EUREKA_URI=http://ds:8761/eureka
      - KAFKA_ADDRESS=cluster_kafka:9092
      - PROFILE=div
    depends_on:
      - discovery
      - kafka
    links:
      - "discovery:ds"
      - "kafka:cluster_kafka"
    restart: unless-stopped

  operation-processor-1:
    build: ./operation-processor
    ports:
      - "8091:8082"
    networks:
      - kafkanetwork
    environment:
      - EUREKA_URI=http://ds:8761/eureka
      - KAFKA_ADDRESS=kafka:9092
      - PROFILE=add
    depends_on:
      - discovery
      - kafka
    links:
      - "discovery:ds"
      - "kafka:cluster_kafka"
    restart: unless-stopped

  operation-processor-2:
    build: ./operation-processor
    ports:
      - "8092:8082"
    networks:
      - kafkanetwork
    environment:
      - EUREKA_URI=http://ds:8761/eureka
      - KAFKA_ADDRESS=kafka:9092
      - PROFILE=sub
    depends_on:
      - discovery
      - kafka
    links:
      - "discovery:ds"
      - "kafka:cluster_kafka"
    restart: unless-stopped

  operation-processor-3:
    build: ./operation-processor
    ports:
      - "8093:8082"
    networks:
      - kafkanetwork
    environment:
      - EUREKA_URI=http://discovery:8761/eureka
      - KAFKA_ADDRESS=kafka:9092
      - PROFILE=mul
    depends_on:
      - discovery
      - kafka
    links:
      - "discovery:ds"
      - "kafka:cluster_kafka"
    restart: unless-stopped

  operation-processor-4:
    build: ./operation-processor
    ports:
      - "8094:8082"
    networks:
      - kafkanetwork
    environment:
      - EUREKA_URI=http://discovery:8761/eureka
      - KAFKA_ADDRESS=kafka:9092
      - PROFILE=div
    depends_on:
      - discovery
      - kafka
    links:
      - "discovery:ds"
      - "kafka:cluster_kafka"
    restart: unless-stopped
    
  kafka-stream-processor:
    build: ./kafka-stream-processor
    ports:
      - "8100:8080"
    networks:
      - kafkanetwork
    depends_on:
      - discovery
      - kafka
    environment:
      - KAFKA_ADDRESS=kafka:9092
    links:
      - "discovery:ds"
      - "kafka:cluster_kafka"
    restart: unless-stopped

networks:
  kafkanetwork:
    driver: bridge
