server:
  port: ${PORT:8088}

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
